<?php

namespace Dotwheel\Db;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-07 at 23:22:18.
 * @coversDefaultClass Dotwheel\Db\Repo
 * @requires PHP 5.4
 */
class RepoTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers ::registerPackage
     * @todo   Implement testRegisterPackage().
     */
    public function testRegisterPackage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::getParam
     * @todo   Implement testGetParam().
     */
    public function testGetParam()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::getLabel
     * @todo   Implement testGetLabel().
     */
    public function testGetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::getList
     * @todo   Implement testGetList().
     */
    public function testGetList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::isArithmetical
     * @todo   Implement testIsArithmetical().
     */
    public function testIsArithmetical()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::isDate
     * @todo   Implement testIsDate().
     */
    public function testIsDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::isTextual
     * @todo   Implement testIsTextual().
     */
    public function testIsTextual()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::validateInput
     * @todo   Implement testValidateInput().
     */
    public function testValidateInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::validatePct
     * @todo   Implement testValidatePct().
     */
    public function testValidatePct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::validatePct100
     * @todo   Implement testValidatePct100().
     */
    public function testValidatePct100()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asHtmlStatic
     * @todo   Implement testAsHtmlStatic().
     */
    public function testAsHtmlStatic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asHtmlInput
     * @todo   Implement testAsHtmlInput().
     */
    public function testAsHtmlInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asSql
     * @todo   Implement testAsSql().
     */
    public function testAsSql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asSqlInt
     * @todo   Implement testAsSqlInt().
     */
    public function testAsSqlInt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asSqlBool
     * @todo   Implement testAsSqlBool().
     */
    public function testAsSqlBool()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asSqlText
     * @todo   Implement testAsSqlText().
     */
    public function testAsSqlText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asSqlSet
     * @todo   Implement testAsSqlSet().
     */
    public function testAsSqlSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::asSqlDate
     * @todo   Implement testAsSqlDate().
     */
    public function testAsSqlDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
