<?php

namespace Dotwheel\Util;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-18 at 17:38:20.
 * @coversDefaultClass Dotwheel\Util\Mime
 * @requires PHP 5.4
 */
class MimeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers ::compileParts
     * @dataProvider compilePartsProvider
     */
    public function testCompileParts($expectedRegex, $parts, $headers)
    {
        $this->assertRegExp($expectedRegex, Mime::compileParts($parts, $headers));
        $this->assertContains('MIME-Version: 1.0', $headers);
    }

    public function compilePartsProvider()
    {
        return [
            'no parts'=>["/^--([^\r]+)\r\n\r\n--\\1--$/", [], []],
            'one part'=>["/^--([^\r]+)\r\nFirst part\r\n--\\1--$/", ['First part'], []],
            'two parts'=>[
                "/^--([^\r]+)\r\nFirst part\r\n--\\1\r\nSecond\r\npart\r\n--\\1--$/",
                ['First part', "Second\r\npart"],
                []
            ],
        ];
    }

    /**
     * @covers ::displayName
     * @dataProvider displayNameProvider
     */
    public function testDisplayName($expected, $name, $charset)
    {
        $this->assertEquals($expected, Mime::displayName($name, $charset));
    }

    public function displayNameProvider()
    {
        return [
            'simple name'=>['Resnick', 'Resnick', 'UTF-8'],
            'double name'=>['Mary Smith', 'Mary Smith', 'UTF-8'],
            'name with punctuation'=>['"Joe Q. Public"', 'Joe Q. Public', 'UTF-8'],
            'name with punctuation2'=>['"Giant; \\"Big\\" \\\\Box"', 'Giant; "Big" \\Box', 'UTF-8'],
            'unicode name'=>['"Jérôme"', 'Jérôme', 'UTF-8'],
        ];
    }

    /**
     * @covers ::partBase64
     * @dataProvider partsProvider
     */
    public function testPartBase64($content, $type)
    {
        $result = Mime::partBase64($content, $type);

        $this->assertContains("Content-Type: $type", $result);
        $this->assertContains("Content-Transfer-Encoding: base64", $result);
        $this->assertContains("\r\n\r\n".\chunk_split(\base64_encode($content)), $result);
    }

    /**
     * @covers ::partQuoted
     * @dataProvider partsProvider
     */
    public function testPartQuoted($content, $type)
    {
        $result = Mime::partQuoted($content, $type);

        $this->assertContains("Content-Type: $type", $result);
        $this->assertContains("Content-Transfer-Encoding: quoted-printable", $result);
        $this->assertContains("\r\n\r\n".\quoted_printable_encode($content), $result);
    }

    public function partsProvider()
    {
        return [
            'empty line'=>['', 'text/plain'],
            'single line'=>['Text', 'text/plain'],
            'long line'=>['A very long line of a somewhat senceless words just to fill some space. And this text may be even longer, and longer, and longer, and longer, and longer, and longer, and longer, and longer, and longer.', 'text/plain'],
        ];
    }
}
