<?php

namespace Dotwheel\Util;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-28 at 00:40:07.
 * @coversDefaultClass Dotwheel\Util\Params
 * @requires PHP 5.4
 */
class ParamsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers ::add
     * @dataProvider addProvider
     */
    public function testAdd($expected, $params, $value, $name, $sep)
    {
        Params::add($params, $value, $name, $sep);
        $this->assertEquals($expected, $params);
    }

    public function addProvider()
    {
        return [
            [['class'=>'active'], '', 'active', 'class', ' '],
            [['class'=>'active'], [], 'active', 'class', ' '],
            [['id'=>'usr', 'class'=>'active'], ['class'=>'active'], 'usr', 'id', ' '],
            [['id'=>'usr', 'class'=>'active'], ['id'=>'usr', 'class'=>'active'], 'active', 'class', ' '],
            [['id'=>'usr', 'class'=>'active second'], ['id'=>'usr', 'class'=>'active'], 'second', 'class', ' '],
            [['style'=>'height:30px;width:100%;'], ['style'=>'height:30px;'], 'width:100%;', 'style', ''],
        ];
    }

    /**
     * @covers ::extract
     * @dataProvider extractProvider
     */
    public function testExtract($expected, $params, $name, $default)
    {
        $result = Params::extract($params, $name, $default);
        $this->assertEquals($expected, $result);
        $this->assertArrayNotHasKey($name, $params);
    }

    public function extractProvider()
    {
        return [
            ['active', ['class'=>'active'], 'class', null],
            [null, ['class'=>'active'], 'id', null],
            ['default', ['class'=>'active'], 'id', 'default'],
        ];
    }
}
