<?php

namespace Dotwheel\Cache;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 21:44:21.
 * @coversDefaultClass Dotwheel\Cache\CacheBase
 * @requires PHP 5.4
 */
class CacheBaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers ::init
     */
    public function testInit()
    {
        $this->assertTrue(CacheInterface::init([
            CacheInterface::P_PREFIX=>'test',
        ]));
    }

    /**
     * @covers ::store
     */
    public function testStore()
    {
        $this->assertTrue(CacheInterface::init([
            CacheInterface::P_PREFIX=>'test',
        ]));
    }

    /**
     * @covers ::storeMulti
     * @todo   Implement testStoreMulti().
     */
    public function testStoreMulti()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::fetchMulti
     * @todo   Implement testFetchMulti().
     */
    public function testFetchMulti()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
